### ISSUE TITLE
How to use this to "actually" install Srain on pop os ( based on Ubuntu)?

### ISSUE THREAD

**Issue by aasutossh** [SilverRainZ/srain-contrib#3]
On `[Installation](https://doc.srain.im/en/latest/install.html#debian)` page it says:
> Move the debian directory to srain’s project root directory, perform the following commands to build a deb package:

It's unclear.

**Comment by tomac4t** [comment]
@aasutossh Are you someone in IRC who asked how to install Srain on Pop!_OS before? This document more about how to packing a deb package. If you want to install the deb package which build by yourself, you can do that like: copy the `debian` folder to the `srain` folder, and then:
```bash
dpkg-buildpackage -b -us -uc; 
cd ..;
sudo apt-get install -f ./`find -name "srain_*.deb"`;
```
Note that you need to install the dependencies which can be found on [debian/crontrol](https://github.com/SrainApp/srain-contrib/blob/master/pack/debian/control). Also note that some Ubuntu packages' name may different than Debian.

**Comment by aasutossh** [comment]
That was me, I was experimenting with my os, I lost (didn't document) the info.
Thanks for this again.

Edit: wasn't there somewhere make command to build it?

**Comment by tomac4t** [comment]
Do you means that `make: command not found`? 

You can install the `make` package via: 
```bash
sudo apt-get install make
```

**Comment by aasutossh** [comment]
> Do you means that `make: command not found`?

I mean wasn't there `make install` or similar command to build and install it?

**Comment by SilverRainZ** [comment]
@aasutossh It was given in the doc you mentioned: https://doc.srain.im/en/latest/install.html#building

**Comment by tomac4t** [comment]
Hey @aasutossh, You may have a problem to package a `.deb` file due to debhelper compat level were specified both in `debian/compat` and `debian/control` files. You can delete the `debian/compat` file and try again. Sorry for inconvenience.

**Comment by tomac4t** [comment]
BTW, We add a [Github workflow](https://github.com/SrainApp/srain/blob/master/.github/workflows/release-debian-package.sh) to upload the Debian package which builds in [Github actions](https://github.com/SrainApp/srain/actions?query=workflow%3Abuild), so It's will be easy to install or remove srain now: 

```bash
# download the latest package from release page: https://github.com/SrainApp/srain/releases
wget https://github.com/SrainApp/srain/releases/download/1.1.0/srain_1.1.0_amd64.deb
# install srain package
sudo apt install -f ./srain_1.1.0_amd64.deb
# remove srain package
sudo apt remove srain
```

**Comment by aasutossh** [comment]
Good stuff. Thank you for the info.
