### ISSUE TITLE
drop Gentoo

### ISSUE THREAD

**Issue by okias** [SilverRainZ/srain-contrib#5]
deprecated, also right now older version is in ::reagentoo overlay and I maintain recent in ::ixit overlay. 

URL with overlay list: https://gpo.zugaina.org/net-im/srain (::ixit is not indexed yet, in few hours I expect to be)

**Comment by SilverRainZ** [comment]
Get it. I will drop it soon.

I have never used gentoo, these overlays (both reagentoo and ixit ) look like unoffical software repo for gentoo? Can you please update the [related document](https://github.com/SrainApp/srain/blob/master/doc/install.rst#gentoo) (or tell me how to update)?

**Comment by SilverRainZ** [comment]
Dropped via c12ee8e.

**Comment by SilverRainZ** [comment]
[Document](https://github.com/SrainApp/srain/blob/ceb5ca3e3dcdea9f7cc238528d770bdf61787687/doc/install.rst#gentoo) updated.
