### ISSUE TITLE
For Debian

### ISSUE THREAD

**Issue by okias** [SilverRainZ/srain-contrib#9]
As a preparation for merging into debian, I actually keep "all-in-one" repository here: https://salsa.debian.org/okias-guest/srain

Building package is easy, just install gbp
```
apt install git-buildpackage
git clone https://salsa.debian.org/okias-guest/srain.git
cd srain
gbp buildpackage # and also apt install dependencies if required
sudo dpkg -i ../srain_*_amd64.deb
```
should be pretty close to debian "production quality".

**Comment by SilverRainZ** [comment]
Good job :tada: :tada: :tada:

**Comment by SilverRainZ** [comment]
https://ftp-master.debian.org/new/srain_1.3.0-1.html

**Comment by SilverRainZ** [comment]
https://packages.debian.org/sid/srain
